#!/bin/sh

# Auto install script for Linux
sudo apt update
###
sudo apt install esptool -y
###
pip install esptool
###
git clone https://github.com/xiv3r/ESP32-wifi-hacker.git
###
cd ESP32-wifi-hacker/bin
###
esptool -b 115200 --before default_reset --after hard_reset --chip esp32 write_flash --flash_mode dio --flash_freq 20m --flash_size detect 0x1000 bootloader.bin 0x8000 partition-table.bin 0x10000 firmware.bin
